services:
  - type: web
    name: ai-quiz-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: ai-quiz-backend
          type: web
          property: url

  - type: web
    name: ai-quiz-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false 